# Generated by Django 2.0.6 on 2018-07-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('MS', 'Middle School'), ('HSL', 'High School-Lower'), ('HSU', 'High School-Upper'), ('C1', 'College-1000'), ('C2', 'College-2000'), ('C3', 'College-3000'), ('C4', 'College-4000'), ('C5', 'College-5000'), ('C6', 'College-6000+')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('BIO', 'Biology'), ('CHE', 'Chemistry'), ('PHY', 'Physics'), ('CSI', 'Computer Science'), ('HIS', 'History')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tag',
            name='level',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagLevel',
        ),
    ]
