# Generated by Django 2.0.6 on 2018-07-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180714_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='courseTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.CourseTag'),
        ),
        migrations.AddField(
            model_name='resource',
            name='levelTags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.LevelTag'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subjectTags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.SubjectTag'),
        ),
    ]
