# Generated by Django 2.0.6 on 2018-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180714_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='levelTags',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='subjectTags',
        ),
        migrations.AddField(
            model_name='resource',
            name='levelTag',
            field=models.CharField(choices=[('MS', 'Middle School'), ('HSL', 'High School-Lower'), ('HSU', 'High School-Upper'), ('C1', 'College-1000'), ('C2', 'College-2000'), ('C3', 'College-3000'), ('C4', 'College-4000'), ('C5', 'College-5000'), ('C6', 'College-6000+')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='subjectTag',
            field=models.CharField(choices=[('BIO', 'Biology'), ('CHE', 'Chemistry'), ('PHY', 'Physics'), ('CSI', 'Computer Science'), ('HIS', 'History')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='LevelTag',
        ),
        migrations.DeleteModel(
            name='SubjectTag',
        ),
    ]
