# Generated by Django 2.0.6 on 2018-07-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180714_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetag',
            name='tagName',
        ),
    ]
