# Generated by Django 2.0.6 on 2018-07-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_coursetag_tagname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNumberTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='courseTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.CourseNumberTag'),
        ),
        migrations.DeleteModel(
            name='CourseTag',
        ),
    ]
