# Generated by Django 2.0.6 on 2018-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180714_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='courseTag',
            field=models.IntegerField(null=True),
        ),
    ]
