# Generated by Django 2.0.6 on 2018-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20180714_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
