# Generated by Django 2.0.6 on 2018-07-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180714_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='courseNumberTag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='courseTag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
