# Generated by Django 2.0.6 on 2018-07-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180714_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='courseNumberTag',
            field=models.IntegerField(blank=True, null=True, verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='courseTag',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='levelTag',
            field=models.CharField(blank=True, choices=[('MS', 'Middle School'), ('HSL', 'High School-Lower'), ('HSU', 'High School-Upper'), ('C1', 'College-1000'), ('C2', 'College-2000'), ('C3', 'College-3000'), ('C4', 'College-4000'), ('C5', 'College-5000'), ('C6', 'College-6000+')], default='', max_length=3, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourceTitle',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subjectTag',
            field=models.CharField(blank=True, choices=[('BIO', 'Biology'), ('CHE', 'Chemistry'), ('PHY', 'Physics'), ('CSI', 'Computer Science'), ('HIS', 'History')], default='', max_length=3, verbose_name='Subject'),
        ),
    ]
