# Generated by Django 2.0.6 on 2018-07-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_resource_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['resourceTitle']},
        ),
    ]
