# Generated by Django 2.0.6 on 2018-07-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180714_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['score']},
        ),
    ]
