# Generated by Django 2.0.6 on 2018-07-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20180715_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='levelTag',
            field=models.CharField(blank=True, choices=[('MS', 'Middle School'), ('HSL', 'High School-Lower'), ('HSU', 'High School-Upper'), ('C1000', 'College-1000'), ('C2000', 'College-2000'), ('C3000', 'College-3000'), ('C4000', 'College-4000'), ('C5000', 'College-5000'), ('C6000', 'College-6000+')], default='', max_length=5, verbose_name='Level'),
        ),
    ]
