# Generated by Django 2.0.6 on 2018-07-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20180715_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='institutionTag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
