# Generated by Django 2.0.6 on 2018-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_resource_institutiontag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='institutionTag',
            field=models.CharField(max_length=50),
        ),
    ]
